name:                png-chunk-yaftee
version:             0.1.0.1
github:              "YoshikuniJujo/png-chunk-yaftee"
license:             BSD-3-Clause
author:              "Yoshikuni Jujo"
maintainer:          "yoshikuni.jujo@gmail.com"
copyright:           "(c) 2025 Yoshikuni Jujo"

extra-source-files:
- README.md

extra-doc-files:
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            PNG's chunk codec on Yaftee
category:            Codec,Graphics,Image

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/YoshikuniJujo/png-chunk-yaftee#readme>

dependencies:
- base >= 4.7 && < 5
- mono-traversable >= 1.0 && < 1.1
- yaftee >= 0.1 && < 0.2
- yaftee-basic-monads >= 0.1 && < 0.2
- yaftee-conduit >= 0.1 && < 0.2
- yaftee-conduit-mono-traversable >= 0.1 && < 0.2
- yaftee-conduit-bytestring >= 0.1 && < 0.2
- yaftee-conduit-bytestring-ft >= 0.1 && < 0.2
- higher-order-open-union >= 0.1 && < 0.2
- bytestring-ft >= 0.1 && < 0.2
- bitarray-bs >= 0.1 && < 0.2
- tools-yj >= 0.1 && < 0.2
- typelevel-tools-yj >= 0.1 && < 0.2

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  png-chunk-yaftee-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - png-chunk-yaftee
